### ISSUE TITLE
可以留一下你的联系方式？

### ISSUE THREAD

**Issue by YangYuHub** [LeoKun1231/nest-cms-api#1]

**Comment by LeoKun1231** [comment]
有什么问题吗？

**Comment by LeoKun1231** [comment]
我的邮箱 1024983409@qq.com

**Comment by YangYuHub** [comment]
![image](https://github.com/LeoKun1231/nest-cms-api/assets/63183404/c7d635f9-9993-415b-abbe-dd78d5912c19)

**Comment by LeoKun1231** [comment]
> ![image](https://private-user-images.githubusercontent.com/63183404/297965406-c7d635f9-9993-415b-abbe-dd78d5912c19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDM4MjgsIm5iZiI6MTcwNTY0MzUyOCwicGF0aCI6Ii82MzE4MzQwNC8yOTc5NjU0MDYtYzdkNjM1ZjktOTk5My00MTViLWFiYmUtZGQ3OGQ1OTEyYzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA1NTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MjQ5YjUzN2U5ZjJhN2QwZDgxYWU2Yjc4NTNmMGUxN2VhYjYxMjI2MTM4NDA1ZjFhOGZkZjBkOTYyODc5ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AwXLFea4w2z1bD5RZQASyh53z-KfV-64QXs3acogCAQ)

截全一点

**Comment by YangYuHub** [comment]
![image](https://github.com/LeoKun1231/nest-cms-api/assets/63183404/50b03735-a6cf-419f-ab2c-8932f979c6f0)

**Comment by LeoKun1231** [comment]
> ![image](https://private-user-images.githubusercontent.com/63183404/297967183-50b03735-a6cf-419f-ab2c-8932f979c6f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDQxODksIm5iZiI6MTcwNTY0Mzg4OSwicGF0aCI6Ii82MzE4MzQwNC8yOTc5NjcxODMtNTBiMDM3MzUtYTZjZi00MTlmLWFiMmMtODkzMmY5NzljNmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA1NTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYTgyZmE2ZTA2MjUzNjU4YTEwNTQwOTdmZDk2ODlkMjhkMTliN2I2OWZlZGRmYWNiMjRhYzM2OWM3ZjY1YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MXy9xqAcQUFOIUvPUI-UVZF3RcomT5S8bt3Pw6pfYWw)

命令行有执行过 pnpm seed 操作吗

**Comment by LeoKun1231** [comment]
> ![image](https://private-user-images.githubusercontent.com/63183404/297967183-50b03735-a6cf-419f-ab2c-8932f979c6f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDQ0OTAsIm5iZiI6MTcwNTY0NDE5MCwicGF0aCI6Ii82MzE4MzQwNC8yOTc5NjcxODMtNTBiMDM3MzUtYTZjZi00MTlmLWFiMmMtODkzMmY5NzljNmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNDQyZDcxODI0ZjZmZDY5NjZjMDJhZmU1ODMwM2YyMjRhZmNmOTliYjA0YzIxNTRlNjc0MDQ1MzVmZmFiMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X6hNvZWSb6iVhf_89MTMcy-Cddg3xBYFXDdxrlpZLoo)

看情况好像是你的生成token那里有问题

**Comment by YangYuHub** [comment]
我是用post man 在本地测试
生成token ，还需要做别的配置？

**Comment by YangYuHub** [comment]
> > ![image](https://private-user-images.githubusercontent.com/63183404/297967183-50b03735-a6cf-419f-ab2c-8932f979c6f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDQ0OTAsIm5iZiI6MTcwNTY0NDE5MCwicGF0aCI6Ii82MzE4MzQwNC8yOTc5NjcxODMtNTBiMDM3MzUtYTZjZi00MTlmLWFiMmMtODkzMmY5NzljNmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNDQyZDcxODI0ZjZmZDY5NjZjMDJhZmU1ODMwM2YyMjRhZmNmOTliYjA0YzIxNTRlNjc0MDQ1MzVmZmFiMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X6hNvZWSb6iVhf_89MTMcy-Cddg3xBYFXDdxrlpZLoo)
> 
> 看情况好像是你的生成token那里有问题



> > ![image](https://private-user-images.githubusercontent.com/63183404/297967183-50b03735-a6cf-419f-ab2c-8932f979c6f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDQxODksIm5iZiI6MTcwNTY0Mzg4OSwicGF0aCI6Ii82MzE4MzQwNC8yOTc5NjcxODMtNTBiMDM3MzUtYTZjZi00MTlmLWFiMmMtODkzMmY5NzljNmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA1NTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYTgyZmE2ZTA2MjUzNjU4YTEwNTQwOTdmZDk2ODlkMjhkMTliN2I2OWZlZGRmYWNiMjRhYzM2OWM3ZjY1YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MXy9xqAcQUFOIUvPUI-UVZF3RcomT5S8bt3Pw6pfYWw)
> 
> 命令行有执行过 pnpm seed 操作吗

有执行

**Comment by LeoKun1231** [comment]
> 我是用post man 在本地测试 生成token ，还需要做别的配置？

你是自己生成密钥的？

**Comment by YangYuHub** [comment]
> > 我是用post man 在本地测试 生成token ，还需要做别的配置？
> 
> 你是自己生成密钥的？

对，用这个生成的
![image](https://github.com/LeoKun1231/nest-cms-api/assets/63183404/6663272a-620b-4e21-82b4-7ece4a3b48b3)

**Comment by LeoKun1231** [comment]
> > > 我是用post man 在本地测试 生成token ，还需要做别的配置？
> > 
> > 
> > 你是自己生成密钥的？
> 
> 对，用这个生成的 ![image](https://private-user-images.githubusercontent.com/63183404/297969457-6663272a-620b-4e21-82b4-7ece4a3b48b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDQ5MDgsIm5iZiI6MTcwNTY0NDYwOCwicGF0aCI6Ii82MzE4MzQwNC8yOTc5Njk0NTctNjY2MzI3MmEtNjIwYi00ZTIxLTgyYjQtN2VjZTRhM2I0OGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMjk3YjczMjJjNzRlMjIwNzJhYjg5ZTI4MjNiMzVjODQ2ZjY5OGNhZjkwNzdkOTJiN2JhM2VlNTljNjBmNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sn-70dPwBvrFtfxrsVMNKTjSerOCN66V45B7_49M2Ho)

![image](https://github.com/LeoKun1231/nest-cms-api/assets/88810970/b0c70e89-3f83-41ba-aade-10f1d2e9ed1f)
这个有操作吗

**Comment by YangYuHub** [comment]
> > > > 我是用post man 在本地测试 生成token ，还需要做别的配置？
> > > 
> > > 
> > > 你是自己生成密钥的？
> > 
> > 
> > 对，用这个生成的 ![image](https://private-user-images.githubusercontent.com/63183404/297969457-6663272a-620b-4e21-82b4-7ece4a3b48b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDQ5MDgsIm5iZiI6MTcwNTY0NDYwOCwicGF0aCI6Ii82MzE4MzQwNC8yOTc5Njk0NTctNjY2MzI3MmEtNjIwYi00ZTIxLTgyYjQtN2VjZTRhM2I0OGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMjk3YjczMjJjNzRlMjIwNzJhYjg5ZTI4MjNiMzVjODQ2ZjY5OGNhZjkwNzdkOTJiN2JhM2VlNTljNjBmNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sn-70dPwBvrFtfxrsVMNKTjSerOCN66V45B7_49M2Ho)
> 
> ![image](https://private-user-images.githubusercontent.com/88810970/297970745-b0c70e89-3f83-41ba-aade-10f1d2e9ed1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDUyODcsIm5iZiI6MTcwNTY0NDk4NywicGF0aCI6Ii84ODgxMDk3MC8yOTc5NzA3NDUtYjBjNzBlODktM2Y4My00MWJhLWFhZGUtMTBmMWQyZTllZDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5OGY3NmYxMWRjOGUwNDYyMGFjNGU1YjNlZjcwZjgxYmQ0ODhkOTY3ZWU0NjdiNTkzNDdlMjg5NGI4YjczNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C-ytGElS8Gu0Uz8qUA7rWC3XGyY1XfcudsWG5w3Pe2U) 这个有操作吗
好了，刚没做这个操作，感谢
