### ISSUE TITLE
生成的表名是大写导致all.sql插入失败,导致需要手动把 department 等改成大写,你的不会吗?

### ISSUE THREAD

**Issue by chanmazi** [LeoKun1231/nest-cms-api#2]

**Comment by LeoKun1231** [comment]
不会，找到问题所在了？

**Comment by FuckScript** [comment]
我觉得应该是你设置是不区分大小写
mysql> describe department;
ERROR 1146 (42S02): Table 'cms.department' doesn't exist
mysql> describe Department;
+----------+--------------+------+-----+----------------------+-------------------+
| Field    | Type         | Null | Key | Default              | Extra             |
+----------+--------------+------+-----+----------------------+-------------------+
| id       | int          | NO   | PRI | NULL                 | auto_increment    |
| name     | varchar(191) | NO   | UNI | NULL                 |                   |
| leader   | varchar(191) | YES  |     | NULL                 |                   |
| enable   | tinyint(1)   | YES  |     | 1                    |                   |
| isDelete | tinyint(1)   | YES  |     | 0                    |                   |
| createAt | datetime(3)  | NO   |     | CURRENT_TIMESTAMP(3) | DEFAULT_GENERATED |
| updateAt | datetime(3)  | NO   |     | NULL                 |                   |
| parentId | int          | YES  | MUL | NULL                 |                   |
+----------+--------------+------+-----+----------------------+-------------------+
8 rows in set (0.02 sec)

**Comment by FuckScript** [comment]
> 不会，找到问题所在了？
没找到,我觉得你应该设置了不区分大小写
mysql> describe department;
ERROR 1146 (42S02): Table 'cms.department' doesn't exist
mysql> describe Department;
+----------+--------------+------+-----+----------------------+-------------------+
| Field | Type | Null | Key | Default | Extra |
+----------+--------------+------+-----+----------------------+-------------------+
| id | int | NO | PRI | NULL | auto_increment |
| name | varchar(191) | NO | UNI | NULL | |
| leader | varchar(191) | YES | | NULL | |
| enable | tinyint(1) | YES | | 1 | |
| isDelete | tinyint(1) | YES | | 0 | |
| createAt | datetime(3) | NO | | CURRENT_TIMESTAMP(3) | DEFAULT_GENERATED |
| updateAt | datetime(3) | NO | | NULL | |
| parentId | int | YES | MUL | NULL | |
+----------+--------------+------+-----+----------------------+-------------------+
8 rows in set (0.02 sec)

**Comment by LeoKun1231** [comment]
有可能哈，可以在model 添加@@map('department')哈



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月8日(星期一) 中午1:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LeoKun1231/nest-cms-api] 生成的表名是大写导致all.sql插入失败,导致需要手动把 department 等改成大写,你的不会吗? (Issue #2)














 
我觉得应该是你设置是不区分大小写
 mysql&gt; describe department;
 ERROR 1146 (42S02): Table 'cms.department' doesn't exist
 mysql&gt; describe Department;
 +----------+--------------+------+-----+----------------------+-------------------+
 | Field    | Type         | Null | Key | Default              | Extra             |
 +----------+--------------+------+-----+----------------------+-------------------+
 | id       | int          | NO   | PRI | NULL                 | auto_increment    |
 | name     | varchar(191) | NO   | UNI | NULL                 |                   |
 | leader   | varchar(191) | YES  |     | NULL                 |                   |
 | enable   | tinyint(1)   | YES  |     | 1                    |                   |
 | isDelete | tinyint(1)   | YES  |     | 0                    |                   |
 | createAt | datetime(3)  | NO   |     | CURRENT_TIMESTAMP(3) | DEFAULT_GENERATED |
 | updateAt | datetime(3)  | NO   |     | NULL                 |                   |
 | parentId | int          | YES  | MUL | NULL                 |                   |
 +----------+--------------+------+-----+----------------------+-------------------+
 8 rows in set (0.02 sec)
