### ISSUE TITLE
奇怪,上周都没问题,知道这是什么原因吗?执行 sudo docker compose -f docker-compose.app.dev.yml up 报的.

### ISSUE THREAD

**Issue by chanmazi** [LeoKun1231/nest-cms-api#3]
<img width="792" alt="image" src="https://github.com/LeoKun1231/nest-cms-api/assets/61317508/563c3bff-b1fd-415b-b63c-f81c9d8cac2c">

**Comment by LeoKun1231** [comment]
检查一下redis是否启动(大概率这个问题)，redis地址是否填对。

**Comment by chanmazi** [comment]
把redis主机改成127.0.0.1报拒绝连接,我命令行又可以连接.

**Comment by FuckScript** [comment]
![Uploading image.png…]()
你看

**Comment by chanmazi** [comment]
<img width="858" alt="image" src="https://github.com/LeoKun1231/nest-cms-api/assets/61317508/5042a12b-fe22-420e-a1bd-a5783bc8e76d">
你看

**Comment by FuckScript** [comment]
![Uploading image.png…]()

**Comment by chanmazi** [comment]
<img width="1332" alt="image" src="https://github.com/LeoKun1231/nest-cms-api/assets/61317508/077cf971-77b0-4007-a123-e3e32c57a79b">

**Comment by LeoKun1231** [comment]
密码改了吗

**Comment by chanmazi** [comment]
> 密码改了吗

123456

**Comment by chanmazi** [comment]
md能加个群二维码吗?

**Comment by LeoKun1231** [comment]
没群。。

> md能加个群二维码吗?

**Comment by LeoKun1231** [comment]
> md能加个群二维码吗?

你加一下我的QQ吧，我远程看看 1024983409
