### ISSUE TITLE
公共api 模块新增

### ISSUE THREAD

**Issue by YangYuHub** [LeoKun1231/nest-cms-api#4]
大佬  这个如果新增一个公共api模块，怎么做呢？
不走token验证的API

**Comment by YangYuHub** [comment]
<img width="774" alt="image" src="https://github.com/LeoKun1231/nest-cms-api/assets/63183404/ce654841-a0d7-4f0e-a71b-c6f661e2646b">
我看有一个这个参数，这个东西怎么使用的呢

**Comment by LeoKun1231** [comment]
> <img alt="image" width="774" src="https://private-user-images.githubusercontent.com/63183404/329236220-ce654841-a0d7-4f0e-a71b-c6f661e2646b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTgwMTYsIm5iZiI6MTcxNTI1NzcxNiwicGF0aCI6Ii82MzE4MzQwNC8zMjkyMzYyMjAtY2U2NTQ4NDEtYTBkNy00ZjBlLWE3MWItYzZmNjYxZTI2NDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEyMjgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ODFhMWQ5MTE5NGIxYWIwNGY5ODU2YWQzNTU5M2M4YTVkNzM1NGQ3YmU2MjA0NDRhN2JjOGIwMTg0MThmZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3uZBQicZRFmfqEJoDBphQBNy9twSRdWZTK0F3ndNWJM"> 我看有一个这个参数，这个东西怎么使用的呢

放在接口上面
![image](https://github.com/LeoKun1231/nest-cms-api/assets/88810970/2b276250-5ae0-4427-8924-19da2e2d0297)
